import type { CaseEvent } from "@/domain/schema";

/**
 * MOCKED continuation of the case, used only to demo the journey progressing
 * past its real-world snapshot (which stops mid-enquiries on 2024-12-13). These
 * are kept deliberately separate from the provided `data/` files so the real
 * feed stays untouched. Most entries are `task.status_changed` events (which the
 * customer timeline filters out); the visible additions are milestones,
 * documents received and messages.
 */

const caseId = "CASE-2024-0847";

const statusChange = (
  id: string,
  timestamp: string,
  taskId: string,
  taskTitle: string,
  fromStatus: string,
  toStatus: string,
  description: string,
): CaseEvent => ({
  id,
  case_id: caseId,
  type: "task.status_changed",
  timestamp,
  actor: "David Chen",
  payload: { task_id: taskId, task_title: taskTitle, from_status: fromStatus, to_status: toStatus },
  description,
});

export const DEMO_FUTURE_EVENTS: CaseEvent[] = [
  // --- Outstanding enquiries resolved ---------------------------------------
  {
    id: "EVT-D01",
    case_id: caseId,
    type: "enquiry.reply_received",
    timestamp: "2024-12-16T10:00:00Z",
    actor: "Blackwood & Associates",
    payload: {
      replies_received: 2,
      outstanding: 0,
      resolved_topics: [
        "Japanese knotweed: professional management plan provided, treatment guaranteed for 5 years.",
        "Loft conversion building regs: certificate unavailable; indemnity insurance policy arranged instead.",
      ],
      still_outstanding: [],
    },
    description: "Final enquiry replies received. Knotweed plan supplied and indemnity policy arranged for the loft.",
  },
  statusChange(
    "EVT-D02",
    "2024-12-16T10:30:00Z",
    "TASK-008",
    "Raise and resolve pre-contract enquiries",
    "in_progress",
    "completed",
    "All pre-contract enquiries resolved.",
  ),
  {
    id: "EVT-D03",
    case_id: caseId,
    type: "milestone.reached",
    timestamp: "2024-12-16T11:00:00Z",
    actor: "system",
    payload: { milestone: "enquiries_resolved", label: "Enquiries Resolved" },
    description: "Every pre-contract enquiry has been answered to your conveyancer's satisfaction.",
  },
  {
    id: "EVT-D04",
    case_id: caseId,
    type: "communication.sent",
    timestamp: "2024-12-16T11:15:00Z",
    actor: "David Chen",
    payload: {
      to: "Sarah Mitchell",
      method: "email",
      subject: "Great news — all enquiries resolved",
      summary:
        "Both remaining enquiries are now resolved. We can report to your lender and start preparing for exchange.",
    },
    description: "Client told that all enquiries are resolved.",
  },

  // --- Report on title to lender --------------------------------------------
  statusChange(
    "EVT-D05",
    "2024-12-17T09:00:00Z",
    "TASK-009",
    "Report on title to mortgage lender",
    "blocked",
    "in_progress",
    "Enquiries resolved; certificate of title to lender now in progress.",
  ),
  statusChange(
    "EVT-D06",
    "2024-12-18T15:00:00Z",
    "TASK-009",
    "Report on title to mortgage lender",
    "in_progress",
    "completed",
    "Certificate of title submitted to Nationwide.",
  ),

  // --- Approve contract & arrange signing -----------------------------------
  statusChange(
    "EVT-D07",
    "2024-12-19T09:00:00Z",
    "TASK-010",
    "Approve contract and arrange signing",
    "not_started",
    "in_progress",
    "Approved contract being prepared for the client to sign.",
  ),
  {
    id: "EVT-D08",
    case_id: caseId,
    type: "communication.sent",
    timestamp: "2024-12-19T09:30:00Z",
    actor: "David Chen",
    payload: {
      to: "Sarah Mitchell",
      method: "email",
      subject: "Your contract is ready to sign",
      summary: "Sent the approved contract for you to review and sign ahead of exchange.",
    },
    description: "Approved contract sent to client for signature.",
  },
  {
    id: "EVT-D09",
    case_id: caseId,
    type: "document.received",
    timestamp: "2024-12-23T14:00:00Z",
    actor: "Sarah Mitchell",
    payload: { document_type: "signed_contract", documents: ["signed_contract"] },
    description: "Signed contract received from client.",
  },
  statusChange(
    "EVT-D10",
    "2024-12-23T14:30:00Z",
    "TASK-010",
    "Approve contract and arrange signing",
    "in_progress",
    "completed",
    "Contract approved and signed by the client.",
  ),

  // --- Deposit --------------------------------------------------------------
  statusChange(
    "EVT-D11",
    "2024-12-23T15:00:00Z",
    "TASK-011",
    "Request deposit funds from client",
    "not_started",
    "in_progress",
    "Deposit funds requested from client.",
  ),
  {
    id: "EVT-D12",
    case_id: caseId,
    type: "communication.sent",
    timestamp: "2024-12-23T15:05:00Z",
    actor: "David Chen",
    payload: {
      to: "Sarah Mitchell",
      method: "email",
      subject: "Deposit funds requested",
      summary: "Requested your £85,000 deposit into our client account ahead of exchange.",
    },
    description: "Deposit funds requested from client.",
  },
  {
    id: "EVT-D13",
    case_id: caseId,
    type: "document.received",
    timestamp: "2025-01-03T11:00:00Z",
    actor: "Sarah Mitchell",
    payload: { document_type: "deposit_funds", amount: 85000 },
    description: "Deposit funds received into the client account.",
  },
  statusChange(
    "EVT-D14",
    "2025-01-03T11:30:00Z",
    "TASK-011",
    "Request deposit funds from client",
    "in_progress",
    "completed",
    "Deposit funds cleared in the client account.",
  ),
  {
    id: "EVT-D15",
    case_id: caseId,
    type: "milestone.reached",
    timestamp: "2025-01-03T12:00:00Z",
    actor: "system",
    payload: { milestone: "ready_to_exchange", label: "Ready to Exchange" },
    description: "Contract signed, deposit held and lender reported to. Ready to exchange.",
  },

  // --- Exchange -------------------------------------------------------------
  statusChange(
    "EVT-D16",
    "2025-01-06T10:00:00Z",
    "TASK-012",
    "Exchange contracts",
    "not_started",
    "in_progress",
    "Exchange of contracts underway.",
  ),
  statusChange(
    "EVT-D17",
    "2025-01-06T15:00:00Z",
    "TASK-012",
    "Exchange contracts",
    "in_progress",
    "completed",
    "Contracts exchanged. Completion date fixed for 10 January 2025.",
  ),
  {
    id: "EVT-D18",
    case_id: caseId,
    type: "milestone.reached",
    timestamp: "2025-01-06T15:05:00Z",
    actor: "system",
    payload: { milestone: "contracts_exchanged", label: "Contracts Exchanged" },
    description: "Contracts are exchanged — the sale is now legally binding, with completion set for 10 January 2025.",
  },
  {
    id: "EVT-D19",
    case_id: caseId,
    type: "communication.sent",
    timestamp: "2025-01-06T15:30:00Z",
    actor: "David Chen",
    payload: {
      to: "Sarah Mitchell",
      method: "phone",
      subject: "We've exchanged!",
      summary: "Contracts are exchanged and completion is booked for 10 January. The purchase is now binding.",
    },
    description: "Client told that contracts have been exchanged.",
  },

  // --- Completion -----------------------------------------------------------
  statusChange(
    "EVT-D20",
    "2025-01-07T09:00:00Z",
    "TASK-013",
    "Request mortgage funds from lender",
    "not_started",
    "in_progress",
    "Mortgage drawdown requested from Nationwide.",
  ),
  statusChange(
    "EVT-D21",
    "2025-01-07T09:05:00Z",
    "TASK-014",
    "Prepare completion statement",
    "not_started",
    "in_progress",
    "Completion statement being prepared.",
  ),
  statusChange(
    "EVT-D22",
    "2025-01-09T16:00:00Z",
    "TASK-013",
    "Request mortgage funds from lender",
    "in_progress",
    "completed",
    "Mortgage funds received from Nationwide.",
  ),
  statusChange(
    "EVT-D23",
    "2025-01-09T16:05:00Z",
    "TASK-014",
    "Prepare completion statement",
    "in_progress",
    "completed",
    "Completion statement finalised and sent to the client.",
  ),
  statusChange(
    "EVT-D24",
    "2025-01-10T10:00:00Z",
    "TASK-015",
    "Complete purchase",
    "not_started",
    "in_progress",
    "Completion monies being sent to the seller's solicitor.",
  ),
  statusChange(
    "EVT-D25",
    "2025-01-10T12:00:00Z",
    "TASK-015",
    "Complete purchase",
    "in_progress",
    "completed",
    "Completion monies received by the seller's solicitor. Keys released.",
  ),
  {
    id: "EVT-D26",
    case_id: caseId,
    type: "milestone.reached",
    timestamp: "2025-01-10T12:05:00Z",
    actor: "system",
    payload: { milestone: "completed", label: "Completed — Keys Released" },
    description: "Completion has taken place. The property is legally yours and the keys have been released.",
  },
  {
    id: "EVT-D27",
    case_id: caseId,
    type: "communication.sent",
    timestamp: "2025-01-10T12:10:00Z",
    actor: "David Chen",
    payload: {
      to: "Sarah Mitchell",
      method: "phone",
      subject: "Congratulations — it's completed!",
      summary: "Completion is done. You can collect the keys from the estate agent. Congratulations on your new home!",
    },
    description: "Client told that completion has taken place.",
  },

  // --- Post-completion ------------------------------------------------------
  statusChange(
    "EVT-D28",
    "2025-01-13T09:00:00Z",
    "TASK-016",
    "Submit stamp duty return and payment",
    "not_started",
    "in_progress",
    "SDLT return being filed with HMRC.",
  ),
  statusChange(
    "EVT-D29",
    "2025-01-14T11:00:00Z",
    "TASK-016",
    "Submit stamp duty return and payment",
    "in_progress",
    "completed",
    "SDLT return filed and stamp duty paid to HMRC.",
  ),
  statusChange(
    "EVT-D30",
    "2025-01-15T09:00:00Z",
    "TASK-017",
    "Register title with Land Registry",
    "not_started",
    "in_progress",
    "Application to register the transfer submitted to Land Registry.",
  ),
  statusChange(
    "EVT-D31",
    "2025-01-20T11:00:00Z",
    "TASK-017",
    "Register title with Land Registry",
    "in_progress",
    "completed",
    "Title registered. You are now the registered owner.",
  ),
  {
    id: "EVT-D32",
    case_id: caseId,
    type: "milestone.reached",
    timestamp: "2025-01-20T11:05:00Z",
    actor: "system",
    payload: { milestone: "registered", label: "Registered with Land Registry" },
    description: "You are now registered as the legal owner of the property. The case is complete.",
  },
];
